/**
 * @project Timadoro
 * @author Hyacinth
 */

package lk.teamtimadoro.timadoro.view;


public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaskDashboard = new javax.swing.JTabbedPane();
        pnlMyTask = new javax.swing.JPanel();
        pnlTimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTasks = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMyStatics = new javax.swing.JPanel();
        pnlTopic = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlNnewWorkspace = new javax.swing.JPanel();
        pnlAboutUs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timadoro");
        setName("frmTimadoroDashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        TaskDashboard.setBackground(new java.awt.Color(255, 255, 255));
        TaskDashboard.setForeground(new java.awt.Color(255, 162, 73));
        TaskDashboard.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TaskDashboard.setFocusTraversalPolicyProvider(true);
        TaskDashboard.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TaskDashboard.setOpaque(true);

        pnlMyTask.setBackground(new java.awt.Color(255, 255, 255));

        pnlTimer.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setText("Timer");

        javax.swing.GroupLayout pnlTimerLayout = new javax.swing.GroupLayout(pnlTimer);
        pnlTimer.setLayout(pnlTimerLayout);
        pnlTimerLayout.setHorizontalGroup(
            pnlTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimerLayout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(428, 428, 428))
        );
        pnlTimerLayout.setVerticalGroup(
            pnlTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimerLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );

        pnlTasks.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tasks");

        javax.swing.GroupLayout pnlTasksLayout = new javax.swing.GroupLayout(pnlTasks);
        pnlTasks.setLayout(pnlTasksLayout);
        pnlTasksLayout.setHorizontalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(417, 417, 417))
        );
        pnlTasksLayout.setVerticalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTasksLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(206, 206, 206))
        );

        javax.swing.GroupLayout pnlMyTaskLayout = new javax.swing.GroupLayout(pnlMyTask);
        pnlMyTask.setLayout(pnlMyTaskLayout);
        pnlMyTaskLayout.setHorizontalGroup(
            pnlMyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMyTaskLayout.setVerticalGroup(
            pnlMyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyTaskLayout.createSequentialGroup()
                .addComponent(pnlTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TaskDashboard.addTab("My Tasks", pnlMyTask);

        pnlMyStatics.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopic.setBackground(new java.awt.Color(255, 204, 153));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("My Daily and Weekly Statics");

        javax.swing.GroupLayout pnlTopicLayout = new javax.swing.GroupLayout(pnlTopic);
        pnlTopic.setLayout(pnlTopicLayout);
        pnlTopicLayout.setHorizontalGroup(
            pnlTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopicLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        pnlTopicLayout.setVerticalGroup(
            pnlTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopicLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMyStaticsLayout = new javax.swing.GroupLayout(pnlMyStatics);
        pnlMyStatics.setLayout(pnlMyStaticsLayout);
        pnlMyStaticsLayout.setHorizontalGroup(
            pnlMyStaticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyStaticsLayout.createSequentialGroup()
                .addGap(0, 503, Short.MAX_VALUE)
                .addComponent(pnlTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMyStaticsLayout.setVerticalGroup(
            pnlMyStaticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyStaticsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(590, Short.MAX_VALUE))
        );

        TaskDashboard.addTab("My Statics", pnlMyStatics);

        pnlNnewWorkspace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlNnewWorkspaceLayout = new javax.swing.GroupLayout(pnlNnewWorkspace);
        pnlNnewWorkspace.setLayout(pnlNnewWorkspaceLayout);
        pnlNnewWorkspaceLayout.setHorizontalGroup(
            pnlNnewWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        pnlNnewWorkspaceLayout.setVerticalGroup(
            pnlNnewWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        TaskDashboard.addTab("My Profile", pnlNnewWorkspace);

        pnlAboutUs.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        TaskDashboard.addTab("About Us", pnlAboutUs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TaskDashboard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TaskDashboard)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TaskDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlMyStatics;
    private javax.swing.JPanel pnlMyTask;
    private javax.swing.JPanel pnlNnewWorkspace;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JPanel pnlTimer;
    private javax.swing.JPanel pnlTopic;
    // End of variables declaration//GEN-END:variables
}
